In [25]:
import torch
from torch import optim
import variationalinference as vi

In [26]:
sigma_e = torch.tensor([2.0, 3.0]) 
mu_e = torch.tensor([-2.0, 3.0]) 
def log_emp_dist(x): 
    return .5*((x - mu_e)**2.0)/(sigma_e ** 2) 
def log_emp_dist_grad(x): 
    return (x - mu_e)/sigma_e**2

In [27]:
svi = vi.DiagGaussianSVI(log_emp_dist, log_emp_dist_grad, 2)

In [29]:
loss = svi.autograd_elbo(svi.vi_mean, svi.vi_log_std)
print(loss)

in forward
tensor([0.0969, 0.0890], grad_fn=<AutogradElboBackward>)


In [30]:
svi.estimate

tensor([0.0969, 0.0890], grad_fn=<AutogradElboBackward>)

In [31]:
svi.log_emp_dist(torch.tensor([1, 2]))

tensor([1.1250, 0.0556])